name: 'Chrome extension upload action'
description: 'upload & publish extensions to the Chrome Web Store'
author: 'mnao305'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
