name: 'Chrome extension upload/publish action'
description: 'upload & publish extensions to the Chrome Web Store'
author: 'chemie2472'
branding:
  color: blue
  icon: upload-cloud
inputs:
  file-path:
    description: 'path & filename to a zip file'
    required: true
  extension-id:
    description: 'extension id'
    required: true
  client-id:
    description: 'client id'
    required: true
  client-secret:
    description: 'client secret'
    required: true
  refresh-token:
    description: 'refresh token'
    required: true
  glob:
    description: 'if true the file can be a glob pattern'
    default: false
  publish:
    description: 'if true upload file and publish'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
